# Generated by b1 (bunnybotv1 agent) for BunnyOS
# Corrected implementation inspired by Ani's professional architecture review.
{ self, inputs, ... }: {
  
  # Export this properly as a NixOS module
  flake.nixosModules.zoteroWebdav = { config, lib, pkgs, ... }:
  let
    cfg = config.services.zotero-webdav;
  in
  {
    options.services.zotero-webdav = {
      enable = lib.mkEnableOption "Zotero WebDAV sync server";
      port = lib.mkOption {
        type = lib.types.port;
        default = 8080;
        description = "Internal port for the WebDAV container.";
      };
      domain = lib.mkOption {
        type = lib.types.str;
        default = "zotero.local"; 
        description = "Your Tailscale or domain name.";
      };
      environmentFile = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Path to a local file containing WEBDAV_PASSWORD=your_password";
      };
    };

    config = lib.mkIf cfg.enable {
      virtualisation.docker.enable = true;

      # Pre-create the persistent directory with perfect permissions (1000:1000)
      systemd.tmpfiles.rules = [
        "d /var/lib/zotero-webdav 0750 1000 1000 -"
      ];

      virtualisation.oci-containers.backend = "docker";
      virtualisation.oci-containers.containers.zotero-webdav = {
        image = "dgraziotin/nginx-webdav-nononsense";
        autoStart = true;
        ports = [
          "127.0.0.1:${toString cfg.port}:80"
        ];
        environment = {
          PUID = "1000";
          PGID = "1000";
          WEBDAV_USERNAME = "zotero"; 
          TZ = "UTC";
        };
        # Load the password from a local file so it isn't tracked in GitHub
        environmentFiles = lib.optional (cfg.environmentFile != null) cfg.environmentFile;
        volumes = [
          "/var/lib/zotero-webdav:/data"
        ];
      };

      # Caddy reverse proxy (Simplified and correct for WebDAV)
      services.caddy = {
        enable = true;
        virtualHosts."http://${cfg.domain}" = {
          extraConfig = ''
            reverse_proxy 127.0.0.1:${toString cfg.port}
          '';
        };
      };

      # Ensure firewall allows HTTP/HTTPS for Caddy
      networking.firewall.allowedTCPPorts = [ 80 443 ];
    };
  };
}
