# Generated by Hermes Agent for BunnyOS
{ config, pkgs, lib, ... }:

{
  options.services.zotero-webdav = {
    enable = lib.mkEnableOption "Zotero WebDAV sync server";
    port = lib.mkOption {
      type = lib.types.port;
      default = 8080;
      description = "Internal port for the WebDAV container.";
    };
    domain = lib.mkOption {
      type = lib.types.str;
      default = "zotero-sync.ts.net";
      description = "Tailscale / Caddy virtual host domain.";
    };
  };

  config = lib.mkIf config.services.zotero-webdav.enable {
    # Enable Podman for running OCI containers
    virtualisation.podman = {
      enable = true;
      dockerCompat = true;
      defaultNetwork.settings.dns_enabled = true;
    };

    # Persistent storage directory
    systemd.tmpfiles.rules = [
      "d /var/lib/zotero-webdav 0750 root root -"
    ];

    # WebDAV container
    virtualisation.oci-containers.backend = "podman";
    virtualisation.oci-containers.containers.zotero-webdav = {
      image = "hurlenko/webdav:latest";
      autoStart = true;
      ports = [
        "127.0.0.1:${toString config.services.zotero-webdav.port}:8080"
      ];
      environment = {
        UID = "0";
        GID = "0";
        USERNAME = "zotero";
        PASSWORD = "change-this-secure-password";
        SCOPE = "/data";
        RO = "false";
        AUTH = "true";
      };
      volumes = [
        "/var/lib/zotero-webdav:/data"
      ];
    };

    # Caddy reverse proxy
    services.caddy = {
      enable = true;
      virtualHosts."${config.services.zotero-webdav.domain}" = {
        extraConfig = ''
          reverse_proxy 127.0.0.1:${toString config.services.zotero-webdav.port} {
            header_up Host {http.reverse_proxy.upstream.host}
            header_up X-Real-IP {http.reverse_proxy.upstream.remote_ip}
          }
        '';
      };
    };

    # Ensure firewall allows HTTP/HTTPS for Tailscale proxy traffic
    networking.firewall.allowedTCPPorts = [ 80 443 ];
  };
}
