# Generated by b1 (bunnybotv1 agent) for BunnyOS
# 
# Usage / Setup Instructions:
# 1. Import module and enable in host configuration (modules/hosts/helios/configuration.nix):
#    services.zotero-webdav.enable = true;
#    services.zotero-webdav.domain = "zotero-sync.ts.net";
#    services.zotero-webdav.environmentFile = "/var/lib/zotero-webdav/env";
# 2. Create secret file at /var/lib/zotero-webdav/env containing:
#    PASSWORD=your-secure-password
# 3. Rebuild NixOS:
#    sudo nixos-rebuild switch --flake .#helios
{ self, inputs, ... }: {
  flake.nixosModules.zoteroWebdav = { config, lib, pkgs, ... }:
  let
    cfg = config.services.zotero-webdav;
  in
  {
    options.services.zotero-webdav = {
      enable = lib.mkEnableOption "Zotero WebDAV sync server";
      port = lib.mkOption {
        type = lib.types.port;
        default = 8080;
        description = "Internal port for the WebDAV container.";
      };
      domain = lib.mkOption {
        type = lib.types.str;
        default = "zotero-sync.ts.net";
        description = "Tailscale / Caddy virtual host domain.";
      };
      environmentFile = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Path to an out-of-store environment file containing secrets (e.g. PASSWORD).";
      };
    };

    config = lib.mkIf cfg.enable {
      # Ensure Docker daemon is enabled for OCI containers
      virtualisation.docker.enable = true;

      # Persistent storage directory
      systemd.tmpfiles.rules = [
        "d /var/lib/zotero-webdav 0750 root root -"
      ];

      # WebDAV container using robust bytemark/webdav image
      virtualisation.oci-containers.backend = "docker";
      virtualisation.oci-containers.containers.zotero-webdav = {
        image = "bytemark/webdav:latest";
        autoStart = true;
        ports = [
          "127.0.0.1:${toString cfg.port}:80"
        ];
        environment = {
          USERNAME = "zotero";
        } // lib.optionalAttrs (cfg.environmentFile == null) {
          PASSWORD = "change-this-secure-password";
        };
        environmentFiles = lib.optional (cfg.environmentFile != null) cfg.environmentFile;
        volumes = [
          "/var/lib/zotero-webdav:/var/webdav"
        ];
      };

      # Caddy reverse proxy
      services.caddy = {
        enable = true;
        virtualHosts."${cfg.domain}" = {
          extraConfig = ''
            reverse_proxy 127.0.0.1:${toString cfg.port} {
              header_up Host {http.reverse_proxy.upstream.host}
              header_up X-Real-IP {http.reverse_proxy.upstream.remote_ip}
            }
          '';
        };
      };

      # Ensure firewall allows HTTP/HTTPS for proxy traffic
      networking.firewall.allowedTCPPorts = [ 80 443 ];
    };
  };
}
